[package]
name = "circus"
version = "0.1.1"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Quantum circuit simulator"
repository = "https://github.com/matthunz/circus-rs"

[dependencies]
rand = "0.8.5"
